version: "2"

linters:
  default: none
  enable:
    - justtrack # Runs the project-specific analyzers.
  settings:
    custom:
      justtrack:
        type: module
        description: runs the JustTrack custom analyzers
        original-url: github.com/justtrackio/go-linters
